### ISSUE TITLE
Enable `!include` syntax in `collection.yaml` and `publication.yaml`

### ISSUE THREAD

**Issue by eldridgejm** [eldridgejm/automata#5]
We should enable something like the below in `publication.yaml`.

```yaml
metadata:
    name: Homework 01

artifacts: !include ../COMMON/artifacts.yaml
```

This will allow us to easily set "defaults" across all publications.

The same should be done for `collection.yaml` and `automata.yaml` for completeness.
